<?php
// teacher/dashboard_data.php — returns JSON for dashboard charts and KPIs (teacher-scoped)
session_start();
require_once __DIR__ . '/../../includes/db.php';
header('Content-Type: application/json; charset=utf-8');

if (empty($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}
$user_id = (int)$_SESSION['user_id'];

/* Sanitize inputs */
$class_id = isset($_POST['class_id']) ? (int)$_POST['class_id'] : null;
$subject_id = isset($_POST['subject_id']) ? (int)$_POST['subject_id'] : null;
$term_id = isset($_POST['term_id']) ? (int)$_POST['term_id'] : null;

/* Determine current term/year if not provided */
if (!$term_id) {
    // try system_settings.default_term
    $default_term_name = null;
    if ($s = $conn->prepare("SELECT setting_value FROM system_settings WHERE setting_key='default_term' LIMIT 1")) {
        $s->execute();
        $default_term_name = $s->get_result()->fetch_row()[0] ?? null;
        $s->close();
    }
    if ($default_term_name) {
        $p = $conn->prepare("SELECT id FROM terms WHERE term_name = ? LIMIT 1");
        if ($p) {
            $p->bind_param('s', $default_term_name);
            $p->execute();
            $rr = $p->get_result()->fetch_row();
            if ($rr) $term_id = (int)$rr[0];
            $p->close();
        }
    }
    if (!$term_id) {
        if ($r = $conn->query("SELECT id FROM terms ORDER BY position LIMIT 1")) {
            $row = $r->fetch_row();
            if ($row) $term_id = (int)$row[0];
        }
    }
}

/* Current academic year */
$current_year_id = null;
if ($r = $conn->query("SELECT id FROM academic_years WHERE is_active = 1 LIMIT 1")) {
    $row = $r->fetch_row();
    if ($row) $current_year_id = (int)$row[0];
}
if (!$current_year_id) {
    if ($p = $conn->prepare("SELECT setting_value FROM system_settings WHERE setting_key='default_academic_year' LIMIT 1")) {
        $p->execute();
        $label = $p->get_result()->fetch_row()[0] ?? null;
        $p->close();
        if ($label) {
            $q = $conn->prepare("SELECT id FROM academic_years WHERE year_label = ? LIMIT 1");
            if ($q) {
                $q->bind_param('s', $label);
                $q->execute();
                $rr = $q->get_result()->fetch_row();
                if ($rr) $current_year_id = (int)$rr[0];
                $q->close();
            }
        }
    }
}

/* Fetch assigned pairs for teacher (class_id, subject_id) */
$assigned_pairs = [];
$stmt = $conn->prepare("SELECT class_id, subject_id FROM teachers_subjects WHERE teacher_id = ?");
$stmt->bind_param('i', $user_id);
$stmt->execute();
$res = $stmt->get_result();
while ($r = $res->fetch_assoc()) $assigned_pairs[] = [(int)$r['class_id'], (int)$r['subject_id']];
$stmt->close();

// If teacher has no assigned pairs, return empty/default JSON
if (empty($assigned_pairs)) {
    echo json_encode([
        'kpis' => ['totalStudents'=>0,'reportsGenerated'=>0,'pendingEntries'=>0,'passRate'=>0],
        'chart1' => ['labels'=>[],'data'=>[]],
        'chart2' => ['labels'=>[],'pass'=>[],'fail'=>[]],
        'alerts' => [],
        'recentReports' => []
    ]);
    exit;
}

/* When specific class/subject filters are provided, validate they are within assigned pairs */
$allowedClassIds = array_unique(array_map(fn($p) => $p[0], $assigned_pairs));
$allowedSubjectIds = array_unique(array_map(fn($p) => $p[1], $assigned_pairs));

// If filter supplied but not allowed, ignore it (security)
if ($class_id && !in_array($class_id, $allowedClassIds, true)) $class_id = null;
if ($subject_id && !in_array($subject_id, $allowedSubjectIds, true)) $subject_id = null;

/* Build class and subject lists to consider */
$considerClassIds = $class_id ? [$class_id] : $allowedClassIds;
$considerSubjectIds = $subject_id ? [$subject_id] : $allowedSubjectIds;

/* KPI: total students in considered classes */
$totalStudents = 0;
if (!empty($considerClassIds)) {
    $in = implode(',', array_map('intval', $considerClassIds));
    $q = $conn->query("SELECT COUNT(*) FROM students WHERE class_id IN ({$in})");
    $totalStudents = (int)$q->fetch_row()[0];
}

/* KPI: reports generated by teacher (reports_log) */
$reportsGenerated = 0;
if ($q = $conn->prepare("SELECT COUNT(*) FROM reports_log WHERE generated_by = ?")) {
    $q->bind_param('i', $user_id);
    $q->execute();
    $reportsGenerated = (int)$q->get_result()->fetch_row()[0];
    $q->close();
}

/* KPI: passRate using scores_summary across considered classes for current term/year */
$passRate = 0.0;
if (!empty($considerClassIds) && $term_id && $current_year_id) {
    $in = implode(',', array_map('intval', $considerClassIds));
    $sql = "SELECT AVG(CASE WHEN average >= 50 THEN 1 ELSE 0 END)*100 AS pass_percent
            FROM scores_summary
            WHERE class_id IN ({$in}) AND term_id = ? AND year_id = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('ii', $term_id, $current_year_id);
    $stmt->execute();
    $val = $stmt->get_result()->fetch_row()[0];
    $passRate = $val !== null ? round((float)$val,1) : 0.0;
    $stmt->close();
}

/* KPI: pendingEntries
   Compute expected entries based on teachers_subjects rows for the considered classes & count actual score rows */
$expectedEntries = 0;
$actualScores = 0;
if (!empty($considerClassIds)) {
    // students per class
    $studentsPerClass = [];
    $inClasses = implode(',', array_map('intval', $considerClassIds));
    if ($r = $conn->query("SELECT class_id, COUNT(*) as cnt FROM students WHERE class_id IN ({$inClasses}) GROUP BY class_id")) {
        while ($row = $r->fetch_assoc()) $studentsPerClass[(int)$row['class_id']] = (int)$row['cnt'];
    }

    // expected entries: sum over teachers_subjects (teacher's assigned pairs) that match consideredClassIds & consideredSubjectIds
    $stmt = $conn->prepare("SELECT class_id FROM teachers_subjects WHERE teacher_id = ? AND class_id IN (" . implode(',', array_map('intval', $considerClassIds)) . ") AND subject_id IN (" . implode(',', array_map('intval', $considerSubjectIds)) . ")");
    $stmt->bind_param('i', $user_id);
    $stmt->execute();
    $res = $stmt->get_result();
    while ($r = $res->fetch_assoc()) {
        $cid = (int)$r['class_id'];
        if (!empty($studentsPerClass[$cid])) $expectedEntries += $studentsPerClass[$cid];
    }
    $stmt->close();

    // actual scores count for considered classes & subjects & term/year
    if ($term_id && $current_year_id) {
        $sql = "SELECT COUNT(*) FROM scores s JOIN students st ON s.student_id = st.id
                WHERE st.class_id IN ({$inClasses}) AND s.subject_id IN (" . implode(',', array_map('intval', $considerSubjectIds)) . ")
                AND s.term_id = ? AND s.year_id = ?";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param('ii', $term_id, $current_year_id);
        $stmt->execute();
        $actualScores = (int)$stmt->get_result()->fetch_row()[0];
        $stmt->close();
    }
}
$pendingEntries = max(0, $expectedEntries - $actualScores);

/* Alerts: missing marks per pair */
$alerts = [];
$total_missing = 0;
foreach ($assigned_pairs as [$cid, $sid]) {
    if (!in_array($cid, $considerClassIds, true)) continue;
    if (!in_array($sid, $considerSubjectIds, true)) continue;

    $studentsCount = 0;
    if ($r = $conn->query("SELECT COUNT(*) FROM students WHERE class_id = " . (int)$cid)) {
        $studentsCount = (int)$r->fetch_row()[0];
    }
    if ($studentsCount === 0) continue;

    // actual entries for this pair
    $have = 0;
    if ($term_id && $current_year_id) {
        $stmt = $conn->prepare("SELECT COUNT(*) FROM scores s JOIN students st ON s.student_id = st.id WHERE st.class_id = ? AND s.subject_id = ? AND s.term_id = ? AND s.year_id = ?");
        $stmt->bind_param('iiii', $cid, $sid, $term_id, $current_year_id);
        $stmt->execute();
        $have = (int)$stmt->get_result()->fetch_row()[0];
        $stmt->close();
    }
    $missing = max(0, $studentsCount - $have);
    $total_missing += $missing;
    if ($missing > 0) {
        // lookup names
        $cname = $conn->query("SELECT class_name FROM classes WHERE id = " . (int)$cid)->fetch_row()[0] ?? "Class {$cid}";
        $sname = $conn->query("SELECT name FROM subjects WHERE id = " . (int)$sid)->fetch_row()[0] ?? "Subject {$sid}";
        $alerts[] = ['type'=>'warning','msg'=> "{$missing} student(s) missing marks in {$sname} ({$cname})"];
    }
}
if ($total_missing > 0) {
    array_unshift($alerts, ['type'=>'danger','msg'=> "{$total_missing} total missing mark(s) across selected assignments."]);
} else {
    $alerts[] = ['type'=>'info','msg'=>'All expected marks present for selected filters.'];
}

/* Recent reports */
$recentReports = [];
$stmt = $conn->prepare("SELECT rl.student_id, rl.report_type, rl.generated_at, s.first_name, s.last_name
                        FROM reports_log rl LEFT JOIN students s ON rl.student_id = s.id
                        WHERE rl.generated_by = ? ORDER BY rl.generated_at DESC LIMIT 10");
$stmt->bind_param('i', $user_id);
$stmt->execute();
$res = $stmt->get_result();
while ($r = $res->fetch_assoc()) {
    $studentName = trim(($r['first_name'] ?? '') . ' ' . ($r['last_name'] ?? ''));
    $recentReports[] = [
        'student' => $studentName ?: ('Student #' . ($r['student_id'] ?? '')),
        'type' => $r['report_type'],
        'generated_at' => $r['generated_at'],
        'download' => null
    ];
}
$stmt->close();

/* Chart 1: class average per subject for considered classes & subjects (term/year) */
$chart1 = ['labels'=>[], 'data'=>[]];
if (!empty($considerSubjectIds) && !empty($considerClassIds) && $term_id && $current_year_id) {
    $inSub = implode(',', array_map('intval', $considerSubjectIds));
    $inCls = implode(',', array_map('intval', $considerClassIds));
    $sql = "SELECT s.subject_id, sub.name, AVG(s.total) AS avg_total
            FROM scores s
            JOIN students st ON s.student_id = st.id
            JOIN subjects sub ON s.subject_id = sub.id
            WHERE s.subject_id IN ({$inSub})
              AND st.class_id IN ({$inCls})
              AND s.term_id = ? AND s.year_id = ?
            GROUP BY s.subject_id, sub.name
            ORDER BY sub.name";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('ii', $term_id, $current_year_id);
    $stmt->execute();
    $res = $stmt->get_result();
    while ($r = $res->fetch_assoc()) {
        $chart1['labels'][] = $r['name'];
        $chart1['data'][] = round((float)$r['avg_total'], 1);
    }
    $stmt->close();
}

/* Chart 2: pass/fail for last 3 terms for considered classes */
$chart2 = ['labels'=>[], 'pass'=>[], 'fail'=>[]];
if (!empty($considerClassIds) && $current_year_id) {
    $terms = [];
    if ($r = $conn->query("SELECT id, term_name FROM terms ORDER BY position DESC LIMIT 3")) {
        while ($t = $r->fetch_assoc()) $terms[] = $t;
    }
    if (!empty($terms)) {
        foreach (array_reverse($terms) as $termRow) {
            $tid = (int)$termRow['id'];
            $chart2['labels'][] = $termRow['term_name'];
            $inCls = implode(',', array_map('intval', $considerClassIds));
            $sql = "SELECT AVG(CASE WHEN average >= 50 THEN 1 ELSE 0 END)*100 AS pass_percent
                    FROM scores_summary
                    WHERE class_id IN ({$inCls}) AND term_id = ? AND year_id = ?";
            $stmt = $conn->prepare($sql);
            $stmt->bind_param('ii', $tid, $current_year_id);
            $stmt->execute();
            $val = $stmt->get_result()->fetch_row()[0];
            $pass = $val !== null ? round((float)$val,1) : 0.0;
            $fail = round(100 - $pass, 1);
            $chart2['pass'][] = $pass;
            $chart2['fail'][] = $fail;
            $stmt->close();
        }
    }
}

/* Build response */
$response = [
    'kpis' => [
        'totalStudents' => $totalStudents,
        'reportsGenerated' => $reportsGenerated,
        'pendingEntries' => $pendingEntries,
        'passRate' => $passRate
    ],
    'chart1' => $chart1,
    'chart2' => $chart2,
    'alerts' => $alerts,
    'recentReports' => $recentReports
];

echo json_encode($response, JSON_UNESCAPED_UNICODE);
exit;
